In [1]:
import pandas as pd

In [2]:
import os
os.getcwd()

'd:\\python_practice\\NLP_basic'

In [3]:
df = pd.read_csv("IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.tail(5)

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

## preprocessing
1. lowercase
2. remove html tags
3. remove urls

In [6]:
df.sample(5)

                                                  review sentiment
3605   I had seen this movie when it got released, an...  positive
17844  **POSSIBLE SPOILERS**<br /><br />The biggest p...  positive
46765  Kairo, or Pulse as it's known amongst English ...  negative
14955  This should be my kind of movie. Even if it su...  negative
32449  Perhaps not Miyazaki's best work, but I couldn...  positive

In [7]:
df["review"].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: str

In [8]:
import re
def remove_html_tags(text):
    pattern = re.compile(r"<.*?>")
    return pattern.sub("", text)

In [9]:
text = "Please <u>underline</u> this important part."

# html tag removal

In [10]:
remove_html_tags(text)

'Please underline this important part.'

In [11]:
df["review"].apply(remove_html_tags)

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str

# remove url

In [12]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r"",text)

In [13]:
text1 = "check out my notebook https://hina.com"
text2 = "check out my notebook https://dummy-domain.net"
text3 = "check out my notebook https://testsite.org"
text4 = "check out my notebook https://example.com"

In [14]:
remove_url(text1)

'check out my notebook '

In [15]:
remove_url(text2)

'check out my notebook '

In [16]:
remove_url(text3)

'check out my notebook '

In [17]:
remove_url(text4)

'check out my notebook '

In [18]:
df["review"].apply(remove_url)

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. <br /><br />The...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str

# remove punctuation
(because during tokenization these marks converted into numbers and resulted increase the size of data so that require to remove)

In [19]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [20]:
exclude = string.punctuation

In [21]:
def remove_punct(text):
    return text.translate(str.maketrans("","",exclude))

In [22]:
text = "Wait, what?! exclaimed Dr. Smith-Jones—the lead NLP scientist at AI_Labs (a subsidiary of TechCorp)."

In [23]:
remove_punct(text)

'Wait what exclaimed Dr SmithJones—the lead NLP scientist at AILabs a subsidiary of TechCorp'

In [24]:
df["review"].apply(remove_punct)

0        One of the other reviewers has mentioned that ...
1        A wonderful little production br br The filmin...
2        I thought this was a wonderful way to spend ti...
3        Basically theres a family where a little boy J...
4        Petter Matteis Love in the Time of Money is a ...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    Im going to have to disagree with the previous...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str

 # chat word treatment

In [25]:
chat_words = {
    "$" : " dollar ",
    "€" : " euro ",
    "4ao" : "for adults only",
    "a.m" : "before midday",
    "a3" : "anytime anywhere anyplace",
    "aamof" : "as a matter of fact",
    "acct" : "account",
    "adih" : "another day in hell",
    "afaic" : "as far as i am concerned",
    "afaict" : "as far as i can tell",
    "afaik" : "as far as i know",
    "afair" : "as far as i remember",
    "afk" : "away from keyboard",
    "app" : "application",
    "approx" : "approximately",
    "apps" : "applications",
    "asap" : "as soon as possible",
    "asl" : "age, sex, location",
    "atk" : "at the keyboard",
    "ave." : "avenue",
    "aymm" : "are you my mother",
    "ayor" : "at your own risk", 
    "b&b" : "bed and breakfast",
    "b+b" : "bed and breakfast",
    "b.c" : "before christ",
    "b2b" : "business to business",
    "b2c" : "business to customer",
    "b4" : "before",
    "b4n" : "bye for now",
    "b@u" : "back at you",
    "bae" : "before anyone else",
    "bak" : "back at keyboard",
    "bbbg" : "bye bye be good",
    "bbc" : "british broadcasting corporation",
    "bbias" : "be back in a second",
    "bbl" : "be back later",
    "bbs" : "be back soon",
    "be4" : "before",
    "bfn" : "bye for now",
    "blvd" : "boulevard",
    "bout" : "about",
    "brb" : "be right back",
    "bros" : "brothers",
    "brt" : "be right there",
    "bsaaw" : "big smile and a wink",
    "btw" : "by the way",
    "bwl" : "bursting with laughter",
    "c/o" : "care of",
    "cet" : "central european time",
    "cf" : "compare",
    "cia" : "central intelligence agency",
    "csl" : "can not stop laughing",
    "cu" : "see you",
    "cul8r" : "see you later",
    "cv" : "curriculum vitae",
    "cwot" : "complete waste of time",
    "cya" : "see you",
    "cyt" : "see you tomorrow",
    "dae" : "does anyone else",
    "dbmib" : "do not bother me i am busy",
    "diy" : "do it yourself",
    "dm" : "direct message",
    "dwh" : "during work hours",
    "e123" : "easy as one two three",
    "eet" : "eastern european time",
    "eg" : "example",
    "embm" : "early morning business meeting",
    "encl" : "enclosed",
    "encl." : "enclosed",
    "etc" : "and so on",
    "faq" : "frequently asked questions",
    "fawc" : "for anyone who cares",
    "fb" : "facebook",
    "fc" : "fingers crossed",
    "fig" : "figure",
    "fimh" : "forever in my heart", 
    "ft." : "feet",
    "ft" : "featuring",
    "ftl" : "for the loss",
    "ftw" : "for the win",
    "fwiw" : "for what it is worth",
    "fyi" : "for your information",
    "g9" : "genius",
    "gahoy" : "get a hold of yourself",
    "gal" : "get a life",
    "gcse" : "general certificate of secondary education",
    "gfn" : "gone for now",
    "gg" : "good game",
    "gl" : "good luck",
    "glhf" : "good luck have fun",
    "gmt" : "greenwich mean time",
    "gmta" : "great minds think alike",
    "gn" : "good night",
    "g.o.a.t" : "greatest of all time",
    "goat" : "greatest of all time",
    "goi" : "get over it",
    "gps" : "global positioning system",
    "gr8" : "great",
    "gratz" : "congratulations",
    "gyal" : "girl",
    "h&c" : "hot and cold",
    "hp" : "horsepower",
    "hr" : "hour",
    "hrh" : "his royal highness",
    "ht" : "height",
    "ibrb" : "i will be right back",
    "ic" : "i see",
    "icq" : "i seek you",
    "icymi" : "in case you missed it",
    "idc" : "i do not care",
    "idgadf" : "i do not give a damn fuck",
    "idgaf" : "i do not give a fuck",
    "idk" : "i do not know",
    "ie" : "that is",
    "i.e" : "that is",
    "ifyp" : "i feel your pain",
    "IG" : "instagram",
    "iirc" : "if i remember correctly",
    "ilu" : "i love you",
    "ily" : "i love you",
    "imho" : "in my humble opinion",
    "imo" : "in my opinion",
    "imu" : "i miss you",
    "iow" : "in other words",
    "irl" : "in real life",
    "j4f" : "just for fun",
    "jic" : "just in case",
    "jk" : "just kidding",
    "jsyk" : "just so you know",
    "l8r" : "later",
    "lb" : "pound",
    "lbs" : "pounds",
    "ldr" : "long distance relationship",
    "lmao" : "laugh my ass off",
    "lmfao" : "laugh my fucking ass off",
    "lol" : "laughing out loud",
    "ltd" : "limited",
    "ltns" : "long time no see",
    "m8" : "mate",
    "mf" : "motherfucker",
    "mfs" : "motherfuckers",
    "mfw" : "my face when",
    "mofo" : "motherfucker",
    "mph" : "miles per hour",
    "mr" : "mister",
    "mrw" : "my reaction when",
    "ms" : "miss",
    "mte" : "my thoughts exactly",
    "nagi" : "not a good idea",
    "nbc" : "national broadcasting company",
    "nbd" : "not big deal",
    "nfs" : "not for sale",
    "ngl" : "not going to lie",
    "nhs" : "national health service",
    "nrn" : "no reply necessary",
    "nsfl" : "not safe for life",
    "nsfw" : "not safe for work",
    "nth" : "nice to have",
    "nvr" : "never",
    "nyc" : "new york city",
    "oc" : "original content",
    "og" : "original",
    "ohp" : "overhead projector",
    "oic" : "oh i see",
    "omdb" : "over my dead body",
    "omg" : "oh my god",
    "omw" : "on my way",
    "p.a" : "per annum",
    "p.m" : "after midday",
    "pm" : "prime minister",
    "poc" : "people of color",
    "pov" : "point of view",
    "pp" : "pages",
    "ppl" : "people",
    "prw" : "parents are watching",
    "ps" : "postscript",
    "pt" : "point",
    "ptb" : "please text back",
    "pto" : "please turn over",
    "qpsa" : "what happens", #"que pasa",
    "ratchet" : "rude",
    "rbtl" : "read between the lines",
    "rlrt" : "real life retweet", 
    "rofl" : "rolling on the floor laughing",
    "roflol" : "rolling on the floor laughing out loud",
    "rotflmao" : "rolling on the floor laughing my ass off",
    "rt" : "retweet",
    "ruok" : "are you ok",
    "sfw" : "safe for work",
    "sk8" : "skate",
    "smh" : "shake my head",
    "sq" : "square",
    "srsly" : "seriously", 
    "ssdd" : "same stuff different day",
    "tbh" : "to be honest",
    "tbs" : "tablespooful",
    "tbsp" : "tablespooful",
    "tfw" : "that feeling when",
    "thks" : "thank you",
    "tho" : "though",
    "thx" : "thank you",
    "tia" : "thanks in advance",
    "til" : "today i learned",
    "tl;dr" : "too long i did not read",
    "tldr" : "too long i did not read",
    "tmb" : "tweet me back",
    "tntl" : "trying not to laugh",
    "ttyl" : "talk to you later",
    "u" : "you",
    "u2" : "you too",
    "u4e" : "yours for ever",
    "utc" : "coordinated universal time",
    "w/" : "with",
    "w/o" : "without",
    "w8" : "wait",
    "wassup" : "what is up",
    "wb" : "welcome back",
    "wtf" : "what the fuck",
    "wtg" : "way to go",
    "wtpa" : "where the party at",
    "wuf" : "where are you from",
    "wuzup" : "what is up",
    "wywh" : "wish you were here",
    "yd" : "yard",
    "ygtr" : "you got that right",
    "ynk" : "you never know",
    "zzz" : "sleeping bored and tired"
}

In [26]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.lower() in chat_words:
            new_text.append(chat_words[w.lower()])
        else:
            new_text.append(w)
    return ' '.join(new_text)

In [27]:
text = "wtg"

In [28]:
chat_conversion(text)

'way to go'

In [29]:
df["review"].apply(chat_conversion)

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. <br /><br />The...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str

# spelling correction

In [30]:
from textblob import TextBlob

In [31]:
incorrect_text  = "there are sevral things and rights abuot humnas but freedmo is esential"
textBlb = TextBlob(incorrect_text)
textBlb.correct().string

'there are several things and rights about humans but freedom is essential'

# removal stopwards
(and,are,or....etc)

In [32]:
from nltk.corpus import stopwords

In [33]:
nltk.download("stopwords")

NameError: name 'nltk' is not defined

In [ ]:
stopwords.words("english")

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [34]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word in stopwords.words("english"):
            new_text.append("")
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return" ".join(x)

In [35]:
text = "sita and geeta are two sisters they love each other but one s tall and another is short so jealousy occur between them"
remove_stopwords(text)

'sita  geeta  two sisters  love    one  tall  another  short  jealousy occur  '

In [36]:
df["review"].apply(remove_stopwords)

KeyboardInterrupt:

# handling emoji
1. remove
2. replace with actual meaning of emoji

In [37]:
import re

def remove_emoji(text):
    
    emoji_pattern = re.compile(
        u"[\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\u2702-\u27B0"          # dingbats ( \U00002702 को \u2702)
        u"\u24C2-\U0001F251"      # enclosed alphanumeric supplemental
        u"]+", flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)


text_data = "Hello world! 😊 Having a great day 🚀🔥 #coding"
clean_text = remove_emoji(text_data)
print(clean_text)
"Hello world!  Having a great day  #coding"

Hello world!  Having a great day  #coding

'Hello world!  Having a great day  #coding'

In [38]:
import emoji
print(emoji.emojize("Hello, World! :thumbs_up:"))

Hello, World! 👍

In [39]:
print(emoji.demojize("Hello, World! 👍:"))

Hello, World! :thumbs_up::

## tokenization
1. word
2. sentence
3. punctuation

still there is problem so we use a library named NLTK to overcome it

In [40]:
text = "my name is mamtu"
tok_en = text.split()
print(tok_en)

['my', 'name', 'is', 'mamtu']

In [41]:
text ="My name is mamtu. I am going to USA this year. Let\'s hope trip to be great."
text.split('.')

['My name is mamtu',
 ' I am going to USA this year',
 " Let's hope trip to be great",
 '']

In [42]:
text ="My name is mamtu. I am going to USA this year. Let\'s hope trip to be great"
text.split('.')

['My name is mamtu',
 ' I am going to USA this year',
 " Let's hope trip to be great"]

In [43]:
text = "my name is mamtu!"
tok_en = text.split()
print(tok_en)

['my', 'name', 'is', 'mamtu!']

In [44]:
text = "where are you going? i am going to USA" 
text.split('.')

['where are you going? i am going to USA']

In [45]:
text = "my name is mamtu!"
tokens= re.findall("[\w']+", text)
tokens

<>:2: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:2: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\USER\AppData\Local\Temp\ipykernel_11716\1812595027.py:2: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  tokens= re.findall("[\w']+", text)

['my', 'name', 'is', 'mamtu']

In [46]:

text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sentences = re.compile(r'[.!?]').split(text)
sentences

['Lorem Ipsum is simply dummy text of the printing and typesetting industry',
 "\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book",
 '']

## NLTK

In [47]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [48]:
import nltk

nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [49]:
from nltk.tokenize import word_tokenize,sent_tokenize

text = "my name is mamtu!"
word_tokenize(text)

# sent_tokens = sent_tokenize(text)

['my', 'name', 'is', 'mamtu', '!']

In [50]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [51]:
sent1 = " i have Ph.D IN A.I"
sent2 = "we're here to help! mail us at nks@gmail.com"
sent3 = "a 5km ride cost $10.50" 
word_tokenize(sent1)

['i', 'have', 'Ph.D', 'IN', 'A.I']

In [52]:
word_tokenize(sent2)

['we',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [53]:
word_tokenize(sent3)

['a', '5km', 'ride', 'cost', '$', '10.50']

## Spacy

In [54]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     - -------------------------------------- 0.5/12.8 MB 3.4 MB/s eta 0:00:04
     --- ------------------------------------ 1.0/12.8 MB 2.9 MB/s eta 0:00:05
     ---- ----------------------------------- 1.6/12.8 MB 2.7 MB/s eta 0:00:05
     ----- ---------------------------------- 1.8/12.8 MB 2.6 MB/s eta 0:00:05
     ------ --------------------------------- 2.1/12.8 MB 2.5 MB/s eta 0:00:05
     ------- -------------------------------- 2.4/12.8 MB 2.1 MB/s eta 0:00:05
     -------- ------------------------------- 2.6/12.8 MB 2.0 MB/s eta 0:00:06
     --------- ------------------------------ 2.9/12.8 MB 1.8 MB/s eta 0:00:06
     --------- ------------------------------ 3.1/12.8 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 3.1/12.8 MB 1.7 MB/s eta 0:00:06
     ---------- ----------------------------- 3.4/12.8 MB 1.5 MB/s eta 0:00:07
     ---------- ----------------------------- 3.4/12.8 MB 1.5 MB/s eta 0:00:07
     ----------- ---------------------------- 3.7/12.8 MB 1.4 MB/s eta 0:00:07
     ------------ --------------------------- 3.9/12.8 MB 1.4 MB/s eta 0:00:07
     ------------ --------------------------- 3.9/12.8 MB 1.4 MB/s eta 0:00:07
     ------------- -------------------------- 4.2/12.8 MB 1.3 MB/s eta 0:00:07
     ------------- -------------------------- 4.2/12.8 MB 1.3 MB/s eta 0:00:07
     ------------- -------------------------- 4.5/12.8 MB 1.2 MB/s eta 0:00:07
     -------------- ------------------------- 4.7/12.8 MB 1.2 MB/s eta 0:00:07
     -------------- ------------------------- 4.7/12.8 MB 1.2 MB/s eta 0:00:07
     --------------- ------------------------ 5.0/12.8 MB 1.1 MB/s eta 0:00:08
     --------------- ------------------------ 5.0/12.8 MB 1.1 MB/s eta 0:00:08
     ---------------- ----------------------- 5.2/12.8 MB 1.1 MB/s eta 0:00:08
     ---------------- ----------------------- 5.2/12.8 MB 1.1 MB/s eta 0:00:08
     ----------------- ---------------------- 5.5/12.8 MB 1.0 MB/s eta 0:00:08
     ----------------- ---------------------- 5.5/12.8 MB 1.0 MB/s eta 0:00:08
     ----------------- ---------------------- 5.5/12.8 MB 1.0 MB/s eta 0:00:08
     ----------------- ---------------------- 5.5/12.8 MB 1.0 MB/s eta 0:00:08
     ----------------- --------------------- 5.8/12.8 MB 959.2 kB/s eta 0:00:08
     ----------------- --------------------- 5.8/12.8 MB 959.2 kB/s eta 0:00:08
     ------------------ -------------------- 6.0/12.8 MB 926.5 kB/s eta 0:00:08
     ------------------- ------------------- 6.3/12.8 MB 920.7 kB/s eta 0:00:08
     ------------------- ------------------- 6.3/12.8 MB 920.7 kB/s eta 0:00:08
     ------------------- ------------------- 6.6/12.8 MB 918.4 kB/s eta 0:00:07
     -------------------- ------------------ 6.8/12.8 MB 914.4 kB/s eta 0:00:07
     -------------------- ------------------ 6.8/12.8 MB 914.4 kB/s eta 0:00:07
     --------------------- ----------------- 7.1/12.8 MB 915.7 kB/s eta 0:00:07
     --------------------- ----------------- 7.1/12.8 MB 915.7 kB/s eta 0:00:07
     ---------------------- ---------------- 7.3/12.8 MB 899.5 kB/s eta 0:00:07
     ---------------------- ---------------- 7.3/12.8 MB 899.5 kB/s eta 0:00:07
     ---------------------- ---------------- 7.3/12.8 MB 899.5 kB/s eta 0:00:07
     ----------------------- --------------- 7.6/12.8 MB 858.3 kB/s eta 0:00:07
     ----------------------- --------------- 7.6/12.8 MB 858.3 kB/s eta 0:00:07
     ----------------------- --------------- 7.6/12.8 MB 858.3 kB/s eta 0:00:07
     ----------------------- --------------- 7.9/12.8 MB 831.3 kB/s eta 0:00:06
     ------------------------ -------------- 8.1/12.8 MB 827.4 kB/s eta 0:00:06
     ------------------------ -------------- 8.1/12.8 MB 827.4 kB/s eta 0:00:06
     ------------------------- ------------- 8.4/12.8 MB 832.5 kB/s eta 0:00:06
     -------------------------- ------------ 8.7/12.8 MB 841.1 kB/s eta 0:00:05
     --------------------------- ----------- 8.9/12.8 MB 844.4 kB/s eta 0:00:05
     --------------------------- ----------- 8.9/12.8 MB 844.4 kB/s eta 0:00:05
     --------------------------- ----------- 9.2/12.8 MB 839.8 kB/s eta 0:00:05
     ---------------------------- ---------- 9.4/12.8 MB 845.6 kB/s eta 0:00:04
     ----------------------------- -------- 10.0/12.8 MB 866.0 kB/s eta 0:00:04
     ------------------------------ ------- 10.2/12.8 MB 872.8 kB/s eta 0:00:03
     ------------------------------- ------ 10.5/12.8 MB 882.9 kB/s eta 0:00:03
     ------------------------------- ------ 10.7/12.8 MB 885.7 kB/s eta 0:00:03
     -------------------------------- ----- 11.0/12.8 MB 889.8 kB/s eta 0:00:03
     --------------------------------- ---- 11.3/12.8 MB 896.6 kB/s eta 0:00:02
     --------------------------------- ---- 11.3/12.8 MB 896.6 kB/s eta 0:00:02
     ---------------------------------- --- 11.5/12.8 MB 897.4 kB/s eta 0:00:02
     ----------------------------------- -- 11.8/12.8 MB 899.1 kB/s eta 0:00:02
     ----------------------------------- -- 12.1/12.8 MB 900.0 kB/s eta 0:00:01
     ----------------------------------- -- 12.1/12.8 MB 900.0 kB/s eta 0:00:01
     ------------------------------------ - 12.3/12.8 MB 902.6 kB/s eta 0:00:01
     -------------------------------------  12.6/12.8 MB 903.0 kB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 905.7 kB/s  0:00:13
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [55]:
doc1 = nlp(sent1)
doc2 = nlp(sent2)
doc3 = nlp(sent3)

In [56]:
for token in doc2:
    print(token)

we
're
here
to
help
!
mail
us
at
nks@gmail.com

## stemming

In [57]:
from nltk.stem.porter import PorterStemmer

In [58]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word)for word in text.split()])

In [59]:
sample ="walk walks walking walked "
stem_words(sample)

'walk walk walk walk'

In [60]:
text = """Natural Language Processing, or NLP, is an exciting field of Artificial Intelligence. It helps computers understand, interpret, and manipulate human language easily! 
Many modern applications like Google Translate, ChatGPT, and Alexa rely heavily on these technologies. However, cleaning raw text data is always the most challenging and time-consuming part of the process. Developers must remove unwanted punctuation, emojis, and stop words before training any machine learning model. 
With the right tools like NLTK and Regex, handling these complex tasks becomes much simpler."""

print(text)

Natural Language Processing, or NLP, is an exciting field of Artificial Intelligence. It helps computers understand, interpret, and manipulate human language easily!
Many modern applications like Google Translate, ChatGPT, and Alexa rely heavily on these technologies. However, cleaning raw text data is always the most challenging and time-consuming part of the process. Developers must remove unwanted punctuation, emojis, and stop words before training any machine learning model.
With the right tools like NLTK and Regex, handling these complex tasks becomes much simpler.

# this is the error in stemming that root word may or may not be in english but in lemmatization that root word is a proper word in english dictionary

In [61]:
stem_words(text)

'natur languag processing, or nlp, is an excit field of artifici intelligence. it help comput understand, interpret, and manipul human languag easily! mani modern applic like googl translate, chatgpt, and alexa reli heavili on these technologies. however, clean raw text data is alway the most challeng and time-consum part of the process. develop must remov unwant punctuation, emojis, and stop word befor train ani machin learn model. with the right tool like nltk and regex, handl these complex task becom much simpler.'

In [62]:
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()
sent = "he was running and eating at same time. he has bad habit of swimming after playing long hours in the sun. he is a runner but he also runs very fast. he is good at swimming and running."
punctuation = "?:!.,;"
sent_words = nltk.word_tokenize(sent)
for word in sent_words:
    if word in punctuation:
        sent_words.remove(word)
sent_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sent_words:
    print("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos = "v")))

Word                Lemma
he                  he
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
he                  he
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
sun                 sun
he                  he
is                  be
a                   a
runner              runner
but                 but
he                  he
also                also
runs                run
very                very
fast                fast
he                  he
is                  be
good                good
at                  at
swimming            swim
and                 and
running             run

In [63]:
df1 = pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})
df1

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [64]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [65]:
bow = cv.fit_transform(df1['text'])

In [66]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [67]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]

In [68]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])

bi-gram

In [69]:
cv = CountVectorizer(ngram_range = (2,2))

In [70]:
bow = cv.fit_transform(df1['text'])

In [71]:
# vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}

In [73]:
cv2 = CountVectorizer(ngram_range = (1,2)) ## it include bigram as well as unigram
bow = cv2.fit_transform(df1['text'])

In [76]:
print(cv2.vocabulary_)
print(len(cv2.vocabulary_))

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}
11

## TF-IDF

In [80]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer()
tfidf.fit_transform(df1['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [ ]:
print(tfidf.idf_)  ## idf constant
print(tfidf.get_feature_names_out()) ## ye idf main 1 ko add krdete h taaki 0 na bna aur tf ka contribution hi ktm na ho

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']